In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn import preprocessing

In [ ]:
df = pd.read_csv('emails.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Columns: 3002 entries, Email No. to Prediction
dtypes: float64(2382), int64(619), object(1)
memory usage: 3.9+ MB


In [ ]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...       0.0  0.0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...       0.0  0.0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...       0.0  0.0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...       0.0  0.0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...       0.0  0.0   

   valued  lay  infrastructure  military  allowing   ff  dry  Prediction  
0     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
1     0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
2     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
3     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
4     0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  

[5 rows x 3002 columns]

In [ ]:
df.dtypes

Email No.      object
the             int64
to              int64
ect             int64
and             int64
               ...   
military      float64
allowing      float64
ff            float64
dry           float64
Prediction    float64
Length: 3002, dtype: object

In [ ]:
df.drop(columns=['Email No.'], inplace=True)

In [ ]:
df.dropna()

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  \
0      0   0    1    0    0   0    2    0    0   0  ...       0.0  0.0   
1      8  13   24    6    6   2  102    1   27  18  ...       0.0  0.0   
2      0   0    1    0    0   0    8    0    0   4  ...       0.0  0.0   
3      0   5   22    0    5   1   51    2   10   1  ...       0.0  0.0   
4      7   6   17    1    5   2   57    0    9   3  ...       0.0  0.0   
..   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...       ...  ...   
165    2   1    1    0    0   3   33    1    0   4  ...       0.0  0.0   
166    0   1    1    0    0   0    6    0    0   1  ...       0.0  0.0   
167    2   2    2    1    5   1   24    2    0   5  ...       0.0  0.0   
168   10   9    3    2    3   3   38    3    0  19  ...       0.0  0.0   
169    1   0    1    0    0   1   23    0    0   4  ...       0.0  1.0   

     valued  lay  infrastructure  military  allowing   ff  dry  Prediction  
0       0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
1       0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
2       0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
3       0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
4       0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
..      ...  ...             ...       ...       ...  ...  ...         ...  
165     0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
166     0.0  0.0             0.0       0.0       0.0  0.0  0.0         1.0  
167     0.0  0.0             0.0       0.0       0.0  0.0  0.0         1.0  
168     0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
169     0.0  0.0             0.0       0.0       0.0  0.0  0.0         1.0  

[170 rows x 3001 columns]

In [ ]:
df.isna().sum()

the           0
to            0
ect           0
and           0
for           0
             ..
military      1
allowing      1
ff            1
dry           1
Prediction    1
Length: 3001, dtype: int64

In [ ]:
df.describe()

the          to         ect         and         for          of  \
count  171.000000  171.000000  171.000000  171.000000  171.000000  171.000000   
mean     6.187135    5.807018    5.251462    2.690058    3.122807    2.298246   
std      8.940987    7.750761    9.133708    4.345771    4.171628    4.279767   
min      0.000000    0.000000    1.000000    0.000000    0.000000    0.000000   
25%      1.000000    1.000000    1.000000    0.000000    1.000000    0.000000   
50%      3.000000    3.000000    2.000000    1.000000    2.000000    1.000000   
75%      7.500000    7.500000    4.500000    3.000000    4.000000    2.500000   
max     60.000000   53.000000   62.000000   23.000000   25.000000   33.000000   

                a         you         hou          in  ...  connevey  \
count  171.000000  171.000000  171.000000  171.000000  ...     170.0   
mean    53.257310    2.116959    2.105263    9.684211  ...       0.0   
std     65.237786    3.714567    4.651442   14.140253  ...       0.0   
min      0.000000    0.000000    0.000000    0.000000  ...       0.0   
25%     15.500000    0.000000    0.000000    1.500000  ...       0.0   
50%     30.000000    1.000000    0.000000    5.000000  ...       0.0   
75%     55.000000    2.000000    2.000000   11.000000  ...       0.0   
max    387.000000   25.000000   27.000000   97.000000  ...       0.0   

              jay  valued         lay  infrastructure  military  allowing  \
count  170.000000   170.0  170.000000           170.0     170.0     170.0   
mean     0.005882     0.0    0.088235             0.0       0.0       0.0   
std      0.076696     0.0    0.623392             0.0       0.0       0.0   
min      0.000000     0.0    0.000000             0.0       0.0       0.0   
25%      0.000000     0.0    0.000000             0.0       0.0       0.0   
50%      0.000000     0.0    0.000000             0.0       0.0       0.0   
75%      0.000000     0.0    0.000000             0.0       0.0       0.0   
max      1.000000     0.0    6.000000             0.0       0.0       0.0   

               ff    dry  Prediction  
count  170.000000  170.0  170.000000  
mean     0.911765    0.0    0.276471  
std      1.560755    0.0    0.448574  
min      0.000000    0.0    0.000000  
25%      0.000000    0.0    0.000000  
50%      0.000000    0.0    0.000000  
75%      1.000000    0.0    1.000000  
max      8.000000    0.0    1.000000  

[8 rows x 3001 columns]

In [ ]:
X=df.iloc[:, :df.shape[1]-1]       #Independent Variables
y=df.iloc[:, -1]                   #Dependent Variable
X.shape, y.shape

((171, 3000), (171,))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=8)

In [ ]:
models = {
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=2),
    "Linear SVM":LinearSVC(random_state=8, max_iter=900000),
    "Polynomical SVM":SVC(kernel="poly", degree=2, random_state=8),
    "RBF SVM":SVC(kernel="rbf", random_state=8),
    "Sigmoid SVM":SVC(kernel="sigmoid", random_state=8)
}

In [ ]:
from sklearn.impute import SimpleImputer

# Instantiate an imputer
imputer = SimpleImputer(strategy='mean')

# Fit and transform the imputer on your training data
X_train = imputer.fit_transform(X_train)

# Transform your test data using the same imputer
X_test = imputer.transform(X_test)

In [ ]:
df.fillna(0, inplace=True)

In [ ]:
for model_name, model in models.items():
    y_pred=model.fit(X_train, y_train).predict(X_test)
    print(f"Accuracy for {model_name} model \t: {metrics.accuracy_score(y_test, y_pred)}")

Accuracy for K-Nearest Neighbors model 	: 0.8800959232613909
Accuracy for Linear SVM model 	: 0.9448441247002398
Accuracy for Polynomical SVM model 	: 0.7529976019184652
Accuracy for RBF SVM model 	: 0.7841726618705036
Accuracy for Sigmoid SVM model 	: 0.6067146282973621


In [ ]:
from sklearn.metrics import classification_report

# Create an empty dictionary to store classification reports
classification_reports = {}

# Iterate through the models and compute classification reports
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred)
    classification_reports[model_name] = report

# Display the classification reports
for model_name, report in classification_reports.items():
    print(f"Classification Report for {model_name}:")
    print(report)
    print()


Classification Report for K-Nearest Neighbors:
              precision    recall  f1-score   support

         0.0       0.91      0.93      0.92       299
         1.0       0.80      0.76      0.78       118

    accuracy                           0.88       417
   macro avg       0.86      0.84      0.85       417
weighted avg       0.88      0.88      0.88       417


Classification Report for Linear SVM:
              precision    recall  f1-score   support

         0.0       0.96      0.97      0.96       299
         1.0       0.91      0.89      0.90       118

    accuracy                           0.94       417
   macro avg       0.93      0.93      0.93       417
weighted avg       0.94      0.94      0.94       417


Classification Report for Polynomical SVM:
              precision    recall  f1-score   support

         0.0       0.75      0.99      0.85       299
         1.0       0.89      0.14      0.25       118

    accuracy                           0.75       41

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

models = {
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=2),
    "Linear SVM": LinearSVC(random_state=8, max_iter=900000),
    "Polynomial SVM": SVC(kernel="poly", degree=2, random_state=8),
    "RBF SVM": SVC(kernel="rbf", random_state=8),
    "Sigmoid SVM": SVC(kernel="sigmoid", random_state=8)
}

# Create an empty dictionary to store confusion matrices
confusion_matrices = {}

# Iterate through the models and compute confusion matrices
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices[model_name] = cm

# Display the confusion matrices
for model_name, cm in confusion_matrices.items():
    print(f"Confusion Matrix for {model_name}:")
    print(cm)
    accuracy = accuracy_score(y_test, models[model_name].predict(X_test))
    print(f"Accuracy for {model_name}: {accuracy}")
    print()


Confusion Matrix for K-Nearest Neighbors:
[[277  22]
 [ 28  90]]
Accuracy for K-Nearest Neighbors: 0.8800959232613909

Confusion Matrix for Linear SVM:
[[289  10]
 [ 13 105]]
Accuracy for Linear SVM: 0.9448441247002398

Confusion Matrix for Polynomial SVM:
[[297   2]
 [101  17]]
Accuracy for Polynomial SVM: 0.7529976019184652

Confusion Matrix for RBF SVM:
[[297   2]
 [ 88  30]]
Accuracy for RBF SVM: 0.7841726618705036

Confusion Matrix for Sigmoid SVM:
[[217  82]
 [ 82  36]]
Accuracy for Sigmoid SVM: 0.6067146282973621

